# Project information
site_name: 'INFO 1601'
site_description: 'INFO 1601 Course Site'
site_author: 'Nicholas Mendez'
site_url: 'https://nmendez.app/info1601'

# Repository
repo_name: 'uwidcit/info1601'
repo_url: 'https://github.com/uwidcit/info1601'

# Copyright
copyright: 'Copyright &copy; 2019 Nicholas Mendez'

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'theme'
  palette:
    primary: 'Blue Grey'
    accent: 'Deep Orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  manifest: 'manifest.json'
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/squidfunk'

# Google Analytics
google_analytics:
  - 'UA-154889698-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized

#PWA Config
use_directory_urls: false
scope: "./"
version: 1.0.0